// <auto-generated />
namespace IdeablogClear.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class user_has_a_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_has_a_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201306131144313_user_has_a_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
