// <auto-generated />
namespace IdeablogClear.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initial_version : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_version));
        
        string IMigrationMetadata.Id
        {
            get { return "201306131140275_initial_version"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
