// <auto-generated />
namespace IdeablogClear.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class topic_created_at_computed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(topic_created_at_computed));
        
        string IMigrationMetadata.Id
        {
            get { return "201306131218378_topic_created_at_computed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
