// <auto-generated />
namespace IdeablogClear.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class created_by_foreign_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(created_by_foreign_key));
        
        string IMigrationMetadata.Id
        {
            get { return "201306131414201_created_by_foreign_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
